#!/bin/bash

#This script will remove the following default Ubuntu 20.04 apps:
##GNOME Mahjongg, Mines, Sudoku, Aisleriot Solitair and, Cheese.

echo "Hello, this script will remove the following applications:
-GNOME Mahjongg
-GNOME Mines
-GNOME Sudoku
-Aisleriot Solitair
-Cheese."

echo -n "Are you sure you want to uninstall these programs? Y/N"
echo
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then

sudo apt-get remove --purge aisleriot -y
sudo apt-get remove --purge gnome-mahjongg -y
sudo apt-get remove --purge gnome-mines -y
sudo apt-get remove --purge gnome-sudoku -y
sudo apt-get remove --purge cheese -y

echo "**Applications successfully removed!"

else
   echo "**Okay, they'll stay put."
fi
